### ISSUE TITLE
Add website in github

### ISSUE THREAD

**Issue by saulshanabrook** [plures/xndtools#6]
Could we add https://xnd.io/ as the website for the github repo?

**Comment by xmnlab** [comment]
@saulshanabrook what do you mean? could you provide more details?

**Comment by saulshanabrook** [comment]
Like this:

<img width="1014" alt="screen shot 2018-08-09 at 6 34 53 pm" src="https://user-images.githubusercontent.com/1186124/43912576-efae7bbc-9c02-11e8-8a23-5c76906e8590.png">


Just so users can click on the link and go to the homepage. Or it could link to https://xnd.readthedocs.io/en/latest/index.html instead of xnd.io

**Comment by xmnlab** [comment]
I think it makes sense. if you agree with that @pearu,  could you do this change?

**Comment by pearu** [comment]
Done.

**Comment by xmnlab** [comment]
thanks @pearu !
